name: Create Extension Release

on:
  push: 
    branches: [release]
jobs:
  cicd:
    name: Create Extension Release
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: execute gitversion
        id: gitversion # step id used as reference for output values
        uses: roryprimrose/rungitversion@v1.0.0
        
      - name: print gitversion
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
      - name: clean install vscode cli
        run: npm ci
      - name: compile and create vsix
        run: npm run package
      - name: print vsix path
        run: |
          echo "VSIX Path: ${{ env.vsix_path }}"
      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: tyd-lang-${{steps.gitversion.outputs.semVer}}.vsix
          path: ${{github.workspace}}/tyd-lang-${{steps.gitversion.outputs.semVer}}.vsix
      
      - name: create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          release_name: v${{ steps.gitversion.outputs.semVer }}
